### ISSUE TITLE
post request params broken

### ISSUE THREAD

**Issue by kostya** [sdogruyol/kemal#257] opened 2016-11-23 18:27 UTC
seems this is after crystal update.

```crystal
require "kemal"

post "/bla" do |env|
  p env.params.body["x"]?
end

Kemal.run
```

curl -s http://127.0.0.1:3000/bla -X POST --data 'x%3D1'
curl -s http://127.0.0.1:3000/bla -X POST --data 'x=1'

nil
nil

works in previous crystal, kemal

**Comment by sdogruyol** [comment] 2016-11-23 18:39
Now this is strange, all the specs are passing 😢

**Comment by airinfection** [comment] 2016-11-23 23:21
My mother always says "don't trust the specs".

**Comment by Fusion** [comment] 2016-11-24 01:48
I can confirm this is broken.
The only way I can retrieve these params is:

    puts env.request.body.as(IO).gets_to_end

I suspect this has to do with Crystal now supporting streaming...

**Comment by Fusion** [comment] 2016-11-24 02:28
(note: for now, one can use this but really I hope we get a cleaner fix ;) )

    env.request.body.as(IO).gets_to_end.split("&").each { |r| k,v=r.split("="); env.params.body[k] ||= v }

**Comment by sdogruyol** [comment] 2016-11-24 09:08
This is now fixed 👍 Thanks everyone for reporting ❤️

**Closed** 2016-11-24 09:07 UTC
Labels: bug

**Comment by airinfection** [comment] 2016-11-24 09:35
❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️

**Comment by airinfection** [comment] 2016-11-24 09:35
❤️S❤️E❤️R❤️D❤️A❤️R❤️ ❤️D❤️O❤️G❤️R❤️U❤️Y❤️O❤️L❤️

**Comment by kostya** [comment] 2016-11-24 13:42
what about spec?

**Comment by sdogruyol** [comment] 2016-11-24 13:44
@kostya the specs are correct, this was due to a behaviour change in `HTTP::Request.body` in Crystal std

**Comment by Fusion** [comment] 2016-11-24 20:12
I think Kostya was asking whether you are going to add a test case for params.body to the specs.

**Comment by sdogruyol** [comment] 2016-11-24 20:17
It's already there @Fusion https://github.com/sdogruyol/kemal/blob/master/spec/param_parser_spec.cr#L53

**Comment by Fusion** [comment] 2016-11-24 20:26
Ooh, nice.
Question: are we definitely comfortable using `gets_to_end`? I mean,  depending on the change in Crystal, you may, down the road, get something other than a FixedLengthContent object.

**Comment by kostya** [comment] 2016-11-24 20:28
this is unit test, i think better to add integration test also, run http server, and run requests. in crystal its quite easy.

**Comment by sdogruyol** [comment] 2016-11-24 20:30
@Fusion i don't think that `HTTP::Server` will get a rewrite like this.

@kostya you are right. I've thought of that but not sure.

**Comment by Fusion** [comment] 2016-11-24 20:32
Thanks, Serdar. That was definitely a nitpick 👍

**Comment by rdp** [comment] 2018-10-04 06:51
FWIW this should also work: ` curl -X POST -H "Content-Type: multipart/form-data; boundary=----------------------------4ebf00fbcf09" -d $'--------------------------4ebf00fbcf09\r\nContent-Disposition: form-data; name="x"\r\n\r\ntest\r\n------------------------------4ebf00fbcf09--\r\n' http://localhost:3000/bla`

However the first example and this one both fail currently...it gives empty `env.params.body` second example works though :)

**Comment by rdp** [comment] 2018-10-06 05:37
OK after some research it appears that `--data 'x%3D1'` should be nil (that's a very long named key, named x=1, with no value) https://stackoverflow.com/questions/52641356/can-you-escape-the-equals-sign-in-post-data for the form-data one filed a new issue, seems unrelated.
